# -*- coding: utf-8 -*-
"""Pandas/Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkCR4TBA0I3h2KxPEHgdjb4RLkkYIRAl
"""

!pip install numpy

import numpy as np

arr = np.array([1])
print(arr)
zero_arr = np.zeros(4)
print(zero_arr)
arr_arrange = np.arange(6,10)
print(arr_arrange)

import numpy as np

arr = np.array([1])
print(arr)
zero_arr = np.zeros(4)
print(zero_arr)
arr_arrange = np.arange(6,10)
print(arr_arrange)


