# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGOee80hGqFEewfaV3U-XxV8e8brumXl
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/Titanic_train.csv")
df.head()
df.describe()
df = pd.read_csv("/content/sample_data/Titanic_train.csv")
df.shape
df.dtypes
df.isnull()
df.isnull().sum()
df.notnull().sum()
df.info()